### PR TITLE
Add missing Bing translator

### PR DESCRIPTION
**Pull request by bocharsky-bw**
Looks like we have Bing translator.

### CODE REVIEW

**Comment by Nyholm** [comment]
@NullIsNot0 this looks okey, right?

@bocharsky-bw could you rebase so we see that the tests are green?

**Comment by NullIsNot0** [comment]
Looks ok to me.

**Comment by bocharsky-bw** [comment]
Thank you for your feedback @NullIsNot0 !

Btw, feel free to "Approve" or "Request changes" even if you're not a part of the organization (yet). You can do it when on "Files changed" tab, see "Review changes" in the top right corner of the page - this will help to understand your opinion on it ;)

**Comment by Nyholm** [comment]
I’ve sent you an invite. If you want to accept. Feel free to merge this PR

**Comment by Nyholm** [comment]
Awesome!

Thank you @NullIsNot0. 
You can use githubs button "squash and merge" to make sure the history looks a little nicer.

**Comment by NullIsNot0** [comment]
OK, thank you! Next time I'll use that button :)

**Pull request merged**
