### PR TITLE
Fix codestyle after uptream release of cs-fixer

### PR DESCRIPTION
**Pull request by rvanlaak**
The default CS-Fixer configurations for `@Symfony` has been updated.

See related comments from https://github.com/php-translation/symfony-bundle/pull/342#issuecomment-549740795 until https://github.com/php-translation/symfony-bundle/pull/342#issuecomment-549928172

If wanted we can also add the related `Makefile` to this PR:

```make
# Makefile

DIR := ${CURDIR}

phpstan:
	docker run --rm -v $(DIR):/project -w /project jakzal/phpqa:php7.1-alpine phpstan analyze

codestyle:
	docker run --rm -v $(DIR):/project -w /project jakzal/phpqa:php7.1-alpine php-cs-fixer fix
```

### CODE REVIEW

**Comment by rvanlaak** [comment]
@welcoMattic that is exactly where #342 focuses on 👍 

This PR is there to get `master` green again because of the upstream change to CS-Fixer.

**Comment by XWB** [comment]
You could also set `no_superfluous_phpdoc_tags` to false. I don't like that the doc comments are getting removed.

**Comment by rvanlaak** [comment]
Same here, although I like that the lines of code gets reduced in this case. But, it is a bit hard to debate personal cs preference 😉

Imho following a standard cs set like the `@Symfony` we currently follow should be the leading choice, so other contributors can know what code style to expect.

Maybe the arguments for choosing `@Symfony` is something to document?

**Comment by XWB** [comment]
> Imho following a standard cs set like the @Symfony we currently follow should be the leading choice, so other contributors can know what code style to expect.

Sure, we could do that. But if the main purpose is to make master green again, setting `no_superfluous_phpdoc_tags` to false would achieve that too without introducing a new CS.

**Comment by rvanlaak** [comment]
Merging this so @ker0x can get his PR #342 green again

**Pull request merged**
