### PR TITLE
Commands should always return int

### PR DESCRIPTION
**Pull request by odolbeau**
All commands must return an integer.
See https://github.com/symfony/symfony/pull/33775

### CODE REVIEW

**Comment by XWB** [comment]
👍

**Comment by XWB** [comment]
@odolbeau Now that https://github.com/php-translation/symfony-bundle/pull/348 is merged, can you rebase so we can validate the unit tests?

**Comment by odolbeau** [comment]
@XWB Done! :+1:

**Comment by welcoMattic** [comment]
Thanks @odolbeau :+1:

**Pull request merged**
