### PR TITLE
Add changelog for 0.3.2

### PR DESCRIPTION
**Pull request by welcoMattic**
Ref #95

### CODE REVIEW

**Comment by Nyholm** [comment]
Thank you. Would you mind adding the rest of the changelog as well?

```
### Changed

- HTML fixes on profiler page

### Added

- Option to not show "unstraslatable" in WebUI
- Make sure we fail with an exception if SfTranslation is not enabled
- Improved testing

### Fixed

- Added translation cache dir on warmup

```

**Comment by welcoMattic** [comment]
Done 👍

**Comment by Nyholm** [comment]
Thank you. I'll just wait for traivs.

**Comment by welcoMattic** [comment]
I just add a little comment in README to precise where load `symfony_profiler` param. I was load it in config.yml, but I experience some issues during `cache:clear` on prod env.

`symfony_profiler` must be enabled only on dev env

**Comment by Nyholm** [comment]
Thank you

**Comment by rvanlaak** [comment]
👍

**Pull request merged**
