### PR TITLE
Try to allow any Twig version

### PR DESCRIPTION
**Pull request by bocharsky-bw**
Let's see if tests pass, but most probably will need to fix some things to make them green with this change

### CODE REVIEW

**Comment by bocharsky-bw** [comment]
Easy win, tests passed now! A lot of good changes were merged lately

**Comment by welcoMattic** [comment]
Well done @bocharsky-bw!

**Comment by XWB** [comment]
The issue is still not resolved for people with Twig though (like almost everyone). Removing dependencies is **not** the solution.

**Comment by bocharsky-bw** [comment]
@XWB wait, what Twig issue are you talking about? Actually, it wasn't a fix, it was just a partial revert of changes I've done before to make tests green. See https://github.com/php-translation/symfony-bundle/pull/313#discussion_r307795497

**Comment by bocharsky-bw** [comment]
And while tests are green now we can focus on specific problems and improve this bundle step by step. And this is one of such steps

**Pull request merged**
