### PR TITLE
chore(travis): disable Composer's memory limit

### PR DESCRIPTION
**Pull request by Kocal**
Some tests are passing again, but other fails because:
  - Twig deprecations since [v2.7.0](https://github.com/twigphp/Twig/releases/tag/v2.7.0) released tomorrow, that makes PHPUnit exit with status code different from 0
  - Sometimes, PHPUnit can't be downloaded from GitHub releases: `PHP Warning:  fopen(https://github.com/sebastianbergmann/phpunit/archive/5.7.zip): failed to open stream: HTTP request failed! HTTP/1.0 404 Not Found
 in /home/travis/build/php-translation/symfony-bundle/vendor/symfony/phpunit-bridge/bin/simple-phpunit on line 62` :man_shrugging: 

**Diff:**
master branch:
Capture d'écran de 2019-03-13 07-41-35

this branch:
Capture d'écran de 2019-03-13 07-41-39

### CODE REVIEW

**Comment by bocharsky-bw** [comment]
Do you have an example (link) where we have memory_limit problem? As I see in this PR `COMPOSER_MEMORY_LIMIT` does not help much with broken tests :/

**Comment by Kocal** [comment]
Yes, these ones from #290 for example:
- https://travis-ci.org/php-translation/symfony-bundle/jobs/505593942
- https://travis-ci.org/php-translation/symfony-bundle/jobs/505593943
- https://travis-ci.org/php-translation/symfony-bundle/jobs/505593944

The same builds on this PR: 
- https://travis-ci.org/php-translation/symfony-bundle/jobs/505600957 still fails but because of a 404 when trying to downloading PHPUnit, but the composer memory limit issue is fixed
- https://travis-ci.org/php-translation/symfony-bundle/jobs/505600958 pass
- https://travis-ci.org/php-translation/symfony-bundle/jobs/505600959 pass too

**Comment by Kocal** [comment]
My bad, I should have done it before! :)

**Comment by bocharsky-bw** [comment]
Thank you @Kocal , I reused your solution in #313 so just merging this to give you a credit

**Comment by Kocal** [comment]
Nice! :slightly_smiling_face:

**Pull request merged**
