### PR TITLE
Prepare release v0.12.4

### LINKED ISSUE #454: New release please
Can you make a new release please this would fix the most deprecation warnings ;)

### PR DESCRIPTION
**Pull request by bocharsky-bw**
Closes #454

### CODE REVIEW

**Comment by rvanlaak** [comment]
Seems `Psr\Http\Client\ClientInterface::sendRequest(Psr\Http\Message\RequestInterface $request)` added the `Psr\Http\Message\ResponseInterface` typehint on the return value. Should that not be considered a BC break from PSR-perspective? Would it require us to pin the PSR package?

**Comment by welcoMattic** [comment]
> Seems `Psr\Http\Client\ClientInterface::sendRequest(Psr\Http\Message\RequestInterface $request)` added the `Psr\Http\Message\ResponseInterface` typehint on the return value. Should that not be considered a BC break from PSR-perspective? Would it require us to pin the PSR package?

As we plan to make a stable release in the coming months, I guess we can pin the PSR package, and update the typehint on the return type in 1.0?

**Comment by bocharsky-bw** [comment]
Hm, in which PR that change you're talking about was done that will cause BC breaks? I don't see this change in the PRs I listed in this release somehow.

**Comment by gimler** [comment]
any news? @welcoMattic @bocharsky-bw

**Comment by tchapi** [comment]
Hello ! 
Any update on this merge so we can have a new release ? Do you need any help ?

Thanks a lot !

**Comment by gimler** [comment]
@rvanlaak can you answer the question from @bocharsky-bw please

**Comment by tchapi** [comment]
I think the typehint was there since the beginning: See the initial commit for this interface here: https://github.com/php-fig/http-client/commit/095050875518a9a9d60f824989cec3a793a720f3#diff-7fe9d7bab1528c58fb39365621c6f02430dd01828c26fe8b00f0408de72c71b8

I don't really see a BC break here, but maybe I'm not lookng at the right thing

**Comment by bocharsky-bw** [comment]
If I understand correctly, the latest bundle's release (which is 0.12.3) also fails on that PHP 8.0 job you mentioned, right? If so, then the latest release has broken tests as well. With the new release, we will just bring some good changes to the users they are so waiting for, but some tests will still fail. I don't think broken tests is a blocker for making releases _if_ those tests are also broken in the latest release, or am I wrong? Probably broken tests will be fixed completely in further releases, and we will make another release with all green tests. Does it make sense? If not, what steps exactly do you suggest to achieve a new release for today?

**Comment by bocharsky-bw** [comment]
All tests were fixed in #458 - please, give a review and share your thoughts

**Comment by bocharsky-bw** [comment]
I think this one is ready now

**Review by welcoMattic — APPROVED** [review]

**Review by welcoMattic — APPROVED** [review]

**Comment by bocharsky-bw** [comment]
Thank you for the review, guys!

**Comment by bocharsky-bw** [comment]
Tag 0.12.4 was created 🎉 

https://github.com/php-translation/symfony-bundle/tree/0.12.4

Thanks everyone for the patience!

**Pull request merged**
