### PR TITLE
Fix Cannot autowire service "php_translation.data_collector" error in…

### PR DESCRIPTION
**Pull request by axi**
Fix Cannot autowire service "php_translation.data_collector" error introduced in d47279e.

See https://github.com/php-translation/symfony-bundle/commit/d47279e2909bfcca8a7801e105e2da8a19b2367d#commitcomment-64500173

### CODE REVIEW

**Review by bocharsky-bw — APPROVED** [review]
Thank you for fixing it!

**Comment by rvanlaak** [comment]
Given that tests did not catch this, could we come up with a functional kernel test for that class?

**Comment by bocharsky-bw** [comment]
Yeah, good idea! It would help to prevent regression. @axi could you try to create a test that would cover this case, please?

**Comment by axi** [comment]
Sorry, I can't think of a test covering this case, don't know where to start

**Comment by rvanlaak** [comment]
Given that this is an external dependency that has to be available as service, it could be as basic as:

```php

class TranslationDataCollectorTest extends BaseTestCase
{
    public function testFetchDataCollector(): void
    {
        $this->bootKernel();
        self::assertTrue($this->getContainer()->has(Symfony\Component\Translation\DataCollector\TranslationDataCollector::class));
    }

**Pull request merged**
