### PR TITLE
Avoid deprecated notice when using symfony/config > 4.2

### PR DESCRIPTION
**Pull request by odolbeau**
More information: https://github.com/symfony/symfony/blob/master/UPGRADE-4.2.md#config

### CODE REVIEW

**Comment by rvanlaak** [comment]
Tests are failing, but I see the test graph is quite big.

@Nyholm what about bumping to Symfony LTS 3.4 and PHP 7.2? 

https://symfony.com/roadmap

That might also be a nice moment to put effort in a v1.0 release.

https://github.com/php-translation/symfony-bundle/issues/252

https://github.com/php-translation/symfony-bundle/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+milestone%3A%22Version+1.0%22

**Comment by odolbeau** [comment]
Tests were failing before this PR, I just removed some deprecation notices. I'll rebase this PR once master will be green if needed.

I'm not sure this PR should be linked to a symfony / PHP version bumping or a coming major release as it's not impacted nor impacting those changes.

Anyway I can propose another PR to bump requirements to `"php":"^7.2"` & `"symfony/*": "^3.4 || ^4.0"` if you want?

**Comment by XWB** [comment]
@Nyholm Can you tag a new release that contains this change?

**Comment by hvt** [comment]
Would indeed be great if a new release could be tagged.

**Pull request merged**
