### PR TITLE
Allow Symfony 7

### PR DESCRIPTION
**Pull request by andreybolonin**
Closes https://github.com/php-translation/symfony-bundle/issues/501

### CODE REVIEW

**Comment by bocharsky-bw** [comment]
Thank you for this PR! Test failures look related, could you rebuild with the latest changes in master branch, I started using Composer v2 in #503

**Comment by bocharsky-bw** [comment]
OK, I rebase with master - now seems failures are related to this PR

**Comment by spiider8** [comment]
Hi, how this PR looks? When wil it be done please?  Thanks ;)

**Comment by bocharsky-bw** [comment]
The problem is that this bundle depends on other bundles that do not have Symfony 7 support yet, e.g:
- https://github.com/php-translation/extractor/pull/172
- https://github.com/php-translation/symfony-storage/pull/64
- https://github.com/php-translation/common/pull/52

So to make this bundle trully support Symfony 7 - we need to add Symfony 7 support to the bundles mentioned above first, make releases for them, and finally merge this PR if tests pass.

I tried to quickly allow Symfony 7 support in those bundles, but as you can see tests failed there. Unfortunately, I don't have time yet to fix them, if anyone wants to be a volunteer to help fixing tests in those packages - please, let me know... or just create a new PR with proper fixes. As soon as we're green - I will be happy to review / merge and move it forward.

**Comment by byhaskell** [comment]
Hello. What is the current status?
I saw that there are recent changes in the named packages, do you need more help?

**Comment by rvanlaak** [comment]
@byhaskell https://github.com/php-translation/extractor/pull/172#issuecomment-1916844118 currently the part where this is stuck.

**Comment by althaus** [comment]
What about a dropping the extractor and using Symfony's `translation:extract` command?

I've haven't checked what the extractor is doing, but it sounds that those two are doing similar things.

**Comment by alcohol** [comment]
If I am not mistaken, this PR can be updated now that the other components support 7+

**Comment by bocharsky-bw** [comment]
I updated this PR with the latest changes in master, but seems we need more work here because some tests fail

@andreybolonin could you take a look?

**Comment by andreybolonin** [comment]
Screenshot 2024-06-18 at 10 57 08

@bocharsky-bw any ideas why?
https://symfony.com/doc/current/reference/twig_reference.html#file-link

**Comment by alcohol** [comment]
> Hm, IIRC that `file_link()` Twig filter comes from `symfony/debug-bundle`, make sure that bundle is installed and enabled for the current Sf env - probably start looking into this direction.

Confirmed: [Symfony/Bundle/WebProfilerBundle/Profiler/CodeExtension.php#L50](https://github.com/symfony/symfony/blob/916718cf368381036ee6bf2ce21930bf7fb67ba2/src/Symfony/Bundle/WebProfilerBundle/Profiler/CodeExtension.php#L50)

**Comment by bocharsky-bw** [comment]
Are you talking about WebUI/show.html.twig? That should be used in dev/test only I think

**Comment by webspin** [comment]
Can you please resolve this issue?

**Comment by pawellen** [comment]
Is closing this topic some message that there wont be any updates to symfony 7 ?

**Comment by bocharsky-bw** [comment]
@pawellen Unfortunately, I don't know the reasons behind closing this PR. Sf 7 support is still a relevant issue for this repo, see #501. Seems no active Symfony 7 PRs currently, so if there are some volunteers who would like to help with it - please, PRs are warmly welcome here!

**Pull request closed without merging**
