### PR TITLE
Add command to delete empty messages

### PR DESCRIPTION
**Pull request by axi**
translation:extract on a new lang currently export keys with empty string as translation, resulting in empty string being valid translations.
I prefer to delete empty translations than having empty string, so fallback can be used

### CODE REVIEW

**Comment by odolbeau** [comment]
Thanks @axi!
Nice move to create a new command to achieve this as it's not the behavior everyone expect.
For example, in my case I voluntary deal with empty translations to allow translators to add (or not) a translation in some places (like form help for example).

Anyway, before merging this PR, could you please add some tests? Thanks!

**Comment by rvanlaak** [comment]
What about extracting the actual behavior of deleting empty messages to it's own class? That will make it testable, reusable and a bit more framework-independent. ;-)

**Comment by Nyholm** [comment]
A small ping. Could you rebase the PR?

**Comment by axi** [comment]
Should be rebased now

**Comment by Nyholm** [comment]
> What about extracting the actual behavior of deleting empty messages to it's own class?

That is true for most (all?) our commands. I see this command is just a copy of `DeleteObsoleteCommand`. 

I think it is fair to merge this and leave the refactoring to a separate PR.

**Pull request merged**
