### PR TITLE
Update docker image used in github actions

### PR DESCRIPTION
**Pull request by odolbeau**

### CODE REVIEW

**Comment by odolbeau** [comment]
@rvanlaak See #374 before merging this please.

**Comment by rvanlaak** [comment]
Imho we could have merged #367 , or add `--prefer-stable` to fix #374

**Comment by odolbeau** [comment]
Not merging #367 make sense and I saw a few repos which have this flag (SensioFrameworkExtraBundle for example https://github.com/sensiolabs/SensioFrameworkExtraBundle/blob/master/composer.json#L46)

Where can we add the `prefer-stable` option?

**Comment by rvanlaak** [comment]
Did push https://github.com/scribbr/symfony-bundle/commit/519680012b238988c36bd3d82dfbeb7220d18ea3 for that. Shall I create a PR for you? You could also cherry-pick it here?

**Comment by odolbeau** [comment]
Looks good for me, don't hesitate to create a PR. :)

**Comment by rvanlaak** [comment]
@odolbeau let's see if #376 passes

**Comment by Nyholm** [comment]
Thank you

**Pull request merged**
