### PR TITLE
Fixed wrong operand precedence

### PR DESCRIPTION
**Pull request by plutonio21**

### CODE REVIEW

**Comment by Nyholm** [comment]
Thank you. 
I know these assignments are not perfect for open source because they might be hard to read. Your parentheses may help. However, they have no effect for the execution. The result will be exactly the same.

**Comment by plutonio21** [comment]
Well, I made this fix because I had errors: instead of extract the right
value provided by the desc filter, it extracted "true", that was converted
to "1" the translation file. Now it works correctly.

**Comment by Nyholm** [comment]
Oh, I might be wrong. 
It was `&& ...`

Anyhow. If you are sure that this will fix your issue then I'm happy to merge. Thank you!

**Comment by plutonio21** [comment]
You are welcome!

**Comment by Nyholm** [comment]
Sure!

**Pull request merged**
