### PR TITLE
Fix tests on Symfony 5.3

### LINKED ISSUE #442: Failed tests on Symfony 5.3
After Symfony 5.3 is released we have some broken tests in master, e.g. see https://github.com/php-translation/symfony-bundle/pull/440/checks?check_run_id=2767886092

I wonder if it's test problems only or this bundle really does not support Symfony 5.3 somehow? Did anyone upgrade their project to 5.3? Does it work well on it?

### PR DESCRIPTION
**Pull request by bocharsky-bw**
A try to fix #442

### CODE REVIEW

**Comment by bocharsky-bw** [comment]
@php-translation/deciders Any ideas on these changes?

**Comment by welcoMattic** [comment]
No ideas, but it seems fixing the tests, so it's ok for me. 
Did the Symfony Profiler was showing deprecation messages about Asset?

**Comment by bocharsky-bw** [comment]
Thank you for looking into it!

No, I haven't noticed any related deprecations on Symfony 5.2, probably I'm missing something? Just in case here's the list of deprecations on tests:
```
./vendor/bin/simple-phpunit                                             ✔  10013  23:46:07
PHPUnit 8.3.5 by Sebastian Bergmann and contributors.

Testing Test Suite
............................................................      60 / 60 (100%)

Time: 13.23 seconds, Memory: 60.00 MB

OK (60 tests, 148 assertions)

Remaining direct deprecation notices (1777)

  390x: Since symfony/dependency-injection 5.1: Not setting the attribute "package" of the "deprecated" option in "/Users/victor/www/github/symfony-bundle/DependencyInjection/../Resources/config/extractors.yaml" is deprecated.
    45x in CheckMissingCommandTest::setUp from Translation\Bundle\Tests\Functional\Command
    15x in BundleInitializationTest::testRegisterBundle from Translation\Bundle\Tests\Functional
    15x in WebUIControllerTest::testCreateAction from Translation\Bundle\Tests\Functional\Controller
    15x in TranslationExtensionTest::testAutoAddEnabled from Translation\Bundle\Tests\Unit\DependencyInjection
    15x in TranslationExtensionTest::testEditInPlaceEnabled from Translation\Bundle\Tests\Unit\DependencyInjection
    15x in TranslationExtensionTest::testSymfonyProfilerEnabled from Translation\Bundle\Tests\Unit\DependencyInjection
    15x in TranslationExtensionTest::testWebUiDisabled from Translation\Bundle\Tests\Unit\DependencyInjection
    15x in TranslationExtensionTest::testWebUiEnabled from Translation\Bundle\Tests\Unit\DependencyInjection
    15x in TranslationExtensionTest::testDefaultLocales from Translation\Bundle\Tests\Unit\DependencyInjection
    15x in TranslationExtensionTest::testLocales from Translation\Bundle\Tests\Unit\DependencyInjection
    15x in WebUIControllerTest::testDeleteAction from Translation\Bundle\Tests\Functional\Controller
    15x in WebUIControllerTest::testEditAction from Translation\Bundle\Tests\Functional\Controller
    15x in WebUIControllerTest::testShowAction from Translation\Bundle\Tests\Functional\Controller
    15x in CatalogueFetcherTest::testFetchCatalogue
    15x in WebUIControllerTest::testIndexAction from Translation\Bundle\Tests\Functional\Controller
    15x in EditInPlaceTest::testDeactivatedTest from Translation\Bundle\Tests\Functional\Controller
    15x in EditInPlaceTest::testIfUntranslatableLabelGetsDisabled from Translation\Bundle\Tests\Functional\Controller
    15x in EditInPlaceTest::testActivatedTest from Translation\Bundle\Tests\Functional\Controller
    15x in EditInPlaceControllerTest::testEditActionError from Translation\Bundle\Tests\Functional\Controller
    15x in EditInPlaceControllerTest::testEditAction from Translation\Bundle\Tests\Functional\Controller
    15x in SyncCommandTest::testExecute from Translation\Bundle\Tests\Functional\Command
    15x in StatusCommandTest::testExecute from Translation\Bundle\Tests\Functional\Command
    15x in ExtractCommandTest::testExecute from Translation\Bundle\Tests\Functional\Command
    15x in TranslationExtensionTest::testFallbackTranslationEnabled from Translation\Bundle\Tests\Unit\DependencyInjection

  390x: Since symfony/dependency-injection 5.1: Not setting the attribute "version" of the "deprecated" option in "/Users/victor/www/github/symfony-bundle/DependencyInjection/../Resources/config/extractors.yaml" is deprecated.
    45x in CheckMissingCommandTest::setUp from Translation\Bundle\Tests\Functional\Command
    15x in BundleInitializationTest::testRegisterBundle from Translation\Bundle\Tests\Functional
    15x in WebUIControllerTest::testCreateAction from Translation\Bundle\Tests\Functional\Controller
    15x in TranslationExtensionTest::testAutoAddEnabled from Translation\Bundle\Tests\Unit\DependencyInjection
    15x in TranslationExtensionTest::testEditInPlaceEnabled from Translation\Bundle\Tests\Unit\DependencyInjection
    15x in TranslationExtensionTest::testSymfonyProfilerEnabled from Translation\Bundle\Tests\Unit\DependencyInjection
    15x in TranslationExtensionTest::testWebUiDisabled from Translation\Bundle\Tests\Unit\DependencyInjection
    15x in TranslationExtensionTest::testWebUiEnabled from Translation\Bundle\Tests\Unit\DependencyInjection
    15x in TranslationExtensionTest::testDefaultLocales from Translation\Bundle\Tests\Unit\DependencyInjection
    15x in TranslationExtensionTest::testLocales from Translation\Bundle\Tests\Unit\DependencyInjection
    15x in WebUIControllerTest::testDeleteAction from Translation\Bundle\Tests\Functional\Controller
    15x in WebUIControllerTest::testEditAction from Translation\Bundle\Tests\Functional\Controller
    15x in WebUIControllerTest::testShowAction from Translation\Bundle\Tests\Functional\Controller
    15x in CatalogueFetcherTest::testFetchCatalogue
    15x in WebUIControllerTest::testIndexAction from Translation\Bundle\Tests\Functional\Controller
    15x in EditInPlaceTest::testDeactivatedTest from Translation\Bundle\Tests\Functional\Controller
    15x in EditInPlaceTest::testIfUntranslatableLabelGetsDisabled from Translation\Bundle\Tests\Functional\Controller
    15x in EditInPlaceTest::testActivatedTest from Translation\Bundle\Tests\Functional\Controller
    15x in EditInPlaceControllerTest::testEditActionError from Translation\Bundle\Tests\Functional\Controller
    15x in EditInPlaceControllerTest::testEditAction from Translation\Bundle\Tests\Functional\Controller
    15x in SyncCommandTest::testExecute from Translation\Bundle\Tests\Functional\Command
    15x in StatusCommandTest::testExecute from Translation\Bundle\Tests\Functional\Command
    15x in ExtractCommandTest::testExecute from Translation\Bundle\Tests\Functional\Command
    15x in TranslationExtensionTest::testFallbackTranslationEnabled from Translation\Bundle\Tests\Unit\DependencyInjection

  260x: Since symfony/dependency-injection 5.1: Not setting the attribute "package" of the "deprecated" option in "/Users/victor/www/github/symfony-bundle/DependencyInjection/../Resources/config/services.yaml" is deprecated.
    30x in CheckMissingCommandTest::setUp from Translation\Bundle\Tests\Functional\Command
    10x in BundleInitializationTest::testRegisterBundle from Translation\Bundle\Tests\Functional
    10x in WebUIControllerTest::testCreateAction from Translation\Bundle\Tests\Functional\Controller
    10x in TranslationExtensionTest::testAutoAddEnabled from Translation\Bundle\Tests\Unit\DependencyInjection
    10x in TranslationExtensionTest::testEditInPlaceEnabled from Translation\Bundle\Tests\Unit\DependencyInjection
    10x in TranslationExtensionTest::testSymfonyProfilerEnabled from Translation\Bundle\Tests\Unit\DependencyInjection
    10x in TranslationExtensionTest::testWebUiDisabled from Translation\Bundle\Tests\Unit\DependencyInjection
    10x in TranslationExtensionTest::testWebUiEnabled from Translation\Bundle\Tests\Unit\DependencyInjection
    10x in TranslationExtensionTest::testDefaultLocales from Translation\Bundle\Tests\Unit\DependencyInjection
    10x in TranslationExtensionTest::testLocales from Translation\Bundle\Tests\Unit\DependencyInjection
    10x in WebUIControllerTest::testDeleteAction from Translation\Bundle\Tests\Functional\Controller
    10x in WebUIControllerTest::testEditAction from Translation\Bundle\Tests\Functional\Controller
    10x in WebUIControllerTest::testShowAction from Translation\Bundle\Tests\Functional\Controller
    10x in CatalogueFetcherTest::testFetchCatalogue
    10x in WebUIControllerTest::testIndexAction from Translation\Bundle\Tests\Functional\Controller
    10x in EditInPlaceTest::testDeactivatedTest from Translation\Bundle\Tests\Functional\Controller
    10x in EditInPlaceTest::testIfUntranslatableLabelGetsDisabled from Translation\Bundle\Tests\Functional\Controller
    10x in EditInPlaceTest::testActivatedTest from Translation\Bundle\Tests\Functional\Controller
    10x in EditInPlaceControllerTest::testEditActionError from Translation\Bundle\Tests\Functional\Controller
    10x in EditInPlaceControllerTest::testEditAction from Translation\Bundle\Tests\Functional\Controller
    10x in SyncCommandTest::testExecute from Translation\Bundle\Tests\Functional\Command
    10x in StatusCommandTest::testExecute from Translation\Bundle\Tests\Functional\Command
    10x in ExtractCommandTest::testExecute from Translation\Bundle\Tests\Functional\Command
    10x in TranslationExtensionTest::testFallbackTranslationEnabled from Translation\Bundle\Tests\Unit\DependencyInjection

  260x: Since symfony/dependency-injection 5.1: Not setting the attribute "version" of the "deprecated" option in "/Users/victor/www/github/symfony-bundle/DependencyInjection/../Resources/config/services.yaml" is deprecated.
    30x in CheckMissingCommandTest::setUp from Translation\Bundle\Tests\Functional\Command
    10x in BundleInitializationTest::testRegisterBundle from Translation\Bundle\Tests\Functional
    10x in WebUIControllerTest::testCreateAction from Translation\Bundle\Tests\Functional\Controller
    10x in TranslationExtensionTest::testAutoAddEnabled from Translation\Bundle\Tests\Unit\DependencyInjection
    10x in TranslationExtensionTest::testEditInPlaceEnabled from Translation\Bundle\Tests\Unit\DependencyInjection
    10x in TranslationExtensionTest::testSymfonyProfilerEnabled from Translation\Bundle\Tests\Unit\DependencyInjection
    10x in TranslationExtensionTest::testWebUiDisabled from Translation\Bundle\Tests\Unit\DependencyInjection
    10x in TranslationExtensionTest::testWebUiEnabled from Translation\Bundle\Tests\Unit\DependencyInjection
    10x in TranslationExtensionTest::testDefaultLocales from Translation\Bundle\Tests\Unit\DependencyInjection
    10x in TranslationExtensionTest::testLocales from Translation\Bundle\Tests\Unit\DependencyInjection
    10x in WebUIControllerTest::testDeleteAction from Translation\Bundle\Tests\Functional\Controller
    10x in WebUIControllerTest::testEditAction from Translation\Bundle\Tests\Functional\Controller
    10x in WebUIControllerTest::testShowAction from Translation\Bundle\Tests\Functional\Controller
    10x in CatalogueFetcherTest::testFetchCatalogue
    10x in WebUIControllerTest::testIndexAction from Translation\Bundle\Tests\Functional\Controller
    10x in EditInPlaceTest::testDeactivatedTest from Translation\Bundle\Tests\Functional\Controller
    10x in EditInPlaceTest::testIfUntranslatableLabelGetsDisabled from Translation\Bundle\Tests\Functional\Controller
    10x in EditInPlaceTest::testActivatedTest from Translation\Bundle\Tests\Functional\Controller
    10x in EditInPlaceControllerTest::testEditActionError from Translation\Bundle\Tests\Functional\Controller
    10x in EditInPlaceControllerTest::testEditAction from Translation\Bundle\Tests\Functional\Controller
    10x in SyncCommandTest::testExecute from Translation\Bundle\Tests\Functional\Command
    10x in StatusCommandTest::testExecute from Translation\Bundle\Tests\Functional\Command
    10x in ExtractCommandTest::testExecute from Translation\Bundle\Tests\Functional\Command
    10x in TranslationExtensionTest::testFallbackTranslationEnabled from Translation\Bundle\Tests\Unit\DependencyInjection

  130x: Since symfony/dependency-injection 5.1: Not setting the attribute "package" of the "deprecated" option in "/Users/victor/www/github/symfony-bundle/DependencyInjection/../Resources/config/console.yaml" is deprecated.
    15x in CheckMissingCommandTest::setUp from Translation\Bundle\Tests\Functional\Command
    5x in BundleInitializationTest::testRegisterBundle from Translation\Bundle\Tests\Functional
    5x in WebUIControllerTest::testCreateAction from Translation\Bundle\Tests\Functional\Controller
    5x in TranslationExtensionTest::testAutoAddEnabled from Translation\Bundle\Tests\Unit\DependencyInjection
    5x in TranslationExtensionTest::testEditInPlaceEnabled from Translation\Bundle\Tests\Unit\DependencyInjection
    5x in TranslationExtensionTest::testSymfonyProfilerEnabled from Translation\Bundle\Tests\Unit\DependencyInjection
    5x in TranslationExtensionTest::testWebUiDisabled from Translation\Bundle\Tests\Unit\DependencyInjection
    5x in TranslationExtensionTest::testWebUiEnabled from Translation\Bundle\Tests\Unit\DependencyInjection
    5x in TranslationExtensionTest::testDefaultLocales from Translation\Bundle\Tests\Unit\DependencyInjection
    5x in TranslationExtensionTest::testLocales from Translation\Bundle\Tests\Unit\DependencyInjection
    5x in WebUIControllerTest::testDeleteAction from Translation\Bundle\Tests\Functional\Controller
    5x in WebUIControllerTest::testEditAction from Translation\Bundle\Tests\Functional\Controller
    5x in WebUIControllerTest::testShowAction from Translation\Bundle\Tests\Functional\Controller
    5x in CatalogueFetcherTest::testFetchCatalogue
    5x in WebUIControllerTest::testIndexAction from Translation\Bundle\Tests\Functional\Controller
    5x in EditInPlaceTest::testDeactivatedTest from Translation\Bundle\Tests\Functional\Controller
    5x in EditInPlaceTest::testIfUntranslatableLabelGetsDisabled from Translation\Bundle\Tests\Functional\Controller
    5x in EditInPlaceTest::testActivatedTest from Translation\Bundle\Tests\Functional\Controller
    5x in EditInPlaceControllerTest::testEditActionError from Translation\Bundle\Tests\Functional\Controller
    5x in EditInPlaceControllerTest::testEditAction from Translation\Bundle\Tests\Functional\Controller
    5x in SyncCommandTest::testExecute from Translation\Bundle\Tests\Functional\Command
    5x in StatusCommandTest::testExecute from Translation\Bundle\Tests\Functional\Command
    5x in ExtractCommandTest::testExecute from Translation\Bundle\Tests\Functional\Command
    5x in TranslationExtensionTest::testFallbackTranslationEnabled from Translation\Bundle\Tests\Unit\DependencyInjection

  130x: Since symfony/dependency-injection 5.1: Not setting the attribute "version" of the "deprecated" option in "/Users/victor/www/github/symfony-bundle/DependencyInjection/../Resources/config/console.yaml" is deprecated.
    15x in CheckMissingCommandTest::setUp from Translation\Bundle\Tests\Functional\Command
    5x in BundleInitializationTest::testRegisterBundle from Translation\Bundle\Tests\Functional
    5x in WebUIControllerTest::testCreateAction from Translation\Bundle\Tests\Functional\Controller
    5x in TranslationExtensionTest::testAutoAddEnabled from Translation\Bundle\Tests\Unit\DependencyInjection
    5x in TranslationExtensionTest::testEditInPlaceEnabled from Translation\Bundle\Tests\Unit\DependencyInjection
    5x in TranslationExtensionTest::testSymfonyProfilerEnabled from Translation\Bundle\Tests\Unit\DependencyInjection
    5x in TranslationExtensionTest::testWebUiDisabled from Translation\Bundle\Tests\Unit\DependencyInjection
    5x in TranslationExtensionTest::testWebUiEnabled from Translation\Bundle\Tests\Unit\DependencyInjection
    5x in TranslationExtensionTest::testDefaultLocales from Translation\Bundle\Tests\Unit\DependencyInjection
    5x in TranslationExtensionTest::testLocales from Translation\Bundle\Tests\Unit\DependencyInjection
    5x in WebUIControllerTest::testDeleteAction from Translation\Bundle\Tests\Functional\Controller
    5x in WebUIControllerTest::testEditAction from Translation\Bundle\Tests\Functional\Controller
    5x in WebUIControllerTest::testShowAction from Translation\Bundle\Tests\Functional\Controller
    5x in CatalogueFetcherTest::testFetchCatalogue
    5x in WebUIControllerTest::testIndexAction from Translation\Bundle\Tests\Functional\Controller
    5x in EditInPlaceTest::testDeactivatedTest from Translation\Bundle\Tests\Functional\Controller
    5x in EditInPlaceTest::testIfUntranslatableLabelGetsDisabled from Translation\Bundle\Tests\Functional\Controller
    5x in EditInPlaceTest::testActivatedTest from Translation\Bundle\Tests\Functional\Controller
    5x in EditInPlaceControllerTest::testEditActionError from Translation\Bundle\Tests\Functional\Controller
    5x in EditInPlaceControllerTest::testEditAction from Translation\Bundle\Tests\Functional\Controller
    5x in SyncCommandTest::testExecute from Translation\Bundle\Tests\Functional\Command
    5x in StatusCommandTest::testExecute from Translation\Bundle\Tests\Functional\Command
    5x in ExtractCommandTest::testExecute from Translation\Bundle\Tests\Functional\Command
    5x in TranslationExtensionTest::testFallbackTranslationEnabled from Translation\Bundle\Tests\Unit\DependencyInjection

  76x: Since symfony/dependency-injection 5.1: Not setting the attribute "package" of the "deprecated" option in "/Users/victor/www/github/symfony-bundle/DependencyInjection/../Resources/config/edit_in_place.yaml" is deprecated.
    12x in CheckMissingCommandTest::setUp from Translation\Bundle\Tests\Functional\Command
    4x in BundleInitializationTest::testRegisterBundle from Translation\Bundle\Tests\Functional
    4x in EditInPlaceTest::testDeactivatedTest from Translation\Bundle\Tests\Functional\Controller
    4x in WebUIControllerTest::testDeleteAction from Translation\Bundle\Tests\Functional\Controller
    4x in WebUIControllerTest::testEditAction from Translation\Bundle\Tests\Functional\Controller
    4x in WebUIControllerTest::testCreateAction from Translation\Bundle\Tests\Functional\Controller
    4x in WebUIControllerTest::testShowAction from Translation\Bundle\Tests\Functional\Controller
    4x in WebUIControllerTest::testIndexAction from Translation\Bundle\Tests\Functional\Controller
    4x in EditInPlaceTest::testActivatedTest from Translation\Bundle\Tests\Functional\Controller
    4x in EditInPlaceTest::testIfUntranslatableLabelGetsDisabled from Translation\Bundle\Tests\Functional\Controller
    4x in CatalogueFetcherTest::testFetchCatalogue
    4x in EditInPlaceControllerTest::testEditActionError from Translation\Bundle\Tests\Functional\Controller
    4x in EditInPlaceControllerTest::testEditAction from Translation\Bundle\Tests\Functional\Controller
    4x in SyncCommandTest::testExecute from Translation\Bundle\Tests\Functional\Command
    4x in StatusCommandTest::testExecute from Translation\Bundle\Tests\Functional\Command
    4x in ExtractCommandTest::testExecute from Translation\Bundle\Tests\Functional\Command
    4x in TranslationExtensionTest::testEditInPlaceEnabled from Translation\Bundle\Tests\Unit\DependencyInjection

  76x: Since symfony/dependency-injection 5.1: Not setting the attribute "version" of the "deprecated" option in "/Users/victor/www/github/symfony-bundle/DependencyInjection/../Resources/config/edit_in_place.yaml" is deprecated.
    12x in CheckMissingCommandTest::setUp from Translation\Bundle\Tests\Functional\Command
    4x in BundleInitializationTest::testRegisterBundle from Translation\Bundle\Tests\Functional
    4x in EditInPlaceTest::testDeactivatedTest from Translation\Bundle\Tests\Functional\Controller
    4x in WebUIControllerTest::testDeleteAction from Translation\Bundle\Tests\Functional\Controller
    4x in WebUIControllerTest::testEditAction from Translation\Bundle\Tests\Functional\Controller
    4x in WebUIControllerTest::testCreateAction from Translation\Bundle\Tests\Functional\Controller
    4x in WebUIControllerTest::testShowAction from Translation\Bundle\Tests\Functional\Controller
    4x in WebUIControllerTest::testIndexAction from Translation\Bundle\Tests\Functional\Controller
    4x in EditInPlaceTest::testActivatedTest from Translation\Bundle\Tests\Functional\Controller
    4x in EditInPlaceTest::testIfUntranslatableLabelGetsDisabled from Translation\Bundle\Tests\Functional\Controller
    4x in CatalogueFetcherTest::testFetchCatalogue
    4x in EditInPlaceControllerTest::testEditActionError from Translation\Bundle\Tests\Functional\Controller
    4x in EditInPlaceControllerTest::testEditAction from Translation\Bundle\Tests\Functional\Controller
    4x in SyncCommandTest::testExecute from Translation\Bundle\Tests\Functional\Command
    4x in StatusCommandTest::testExecute from Translation\Bundle\Tests\Functional\Command
    4x in ExtractCommandTest::testExecute from Translation\Bundle\Tests\Functional\Command
    4x in TranslationExtensionTest::testEditInPlaceEnabled from Translation\Bundle\Tests\Unit\DependencyInjection

  65x: Since symfony/http-foundation 5.3: "Symfony\Component\HttpFoundation\RequestStack::getMasterRequest()" is deprecated, use "getMainRequest()" instead.
    14x in EditInPlaceTest::testActivatedTest from Translation\Bundle\Tests\Functional\Controller
    12x in CheckMissingCommandTest::testReportsEmptyTranslationMessages from Translation\Bundle\Tests\Functional\Command
    8x in EditInPlaceTest::testIfUntranslatableLabelGetsDisabled from Translation\Bundle\Tests\Functional\Controller
    8x in EditInPlaceTest::testDeactivatedTest from Translation\Bundle\Tests\Functional\Controller
    6x in CheckMissingCommandTest::testReportsMissingTranslations from Translation\Bundle\Tests\Functional\Command
    6x in CheckMissingCommandTest::testReportsNoNewTranslationMessages from Translation\Bundle\Tests\Functional\Command
    6x in ExtractCommandTest::testExecute from Translation\Bundle\Tests\Functional\Command
    3x in EditInPlaceTranslatorTest::testHtmlTranslation from Translation\Bundle\Tests\Unit\Translator
    1x in EditInPlaceTranslatorTest::testEnabled from Translation\Bundle\Tests\Unit\Translator
    1x in EditInPlaceTranslatorTest::testDisabled from Translation\Bundle\Tests\Unit\Translator

Remaining indirect deprecation notices (51)

  18x: Since symfony/dependency-injection 5.1: The "Psr\Container\ContainerInterface" autowiring alias is deprecated. Define it explicitly in your app if you want to keep using it. It is being referenced by the "Translation\Bundle\Controller\WebUIController" service.
    3x in CheckMissingCommandTest::setUp from Translation\Bundle\Tests\Functional\Command
    1x in BundleInitializationTest::testRegisterBundle from Translation\Bundle\Tests\Functional
    1x in CatalogueFetcherTest::testFetchCatalogue
    1x in ExtractCommandTest::testExecute from Translation\Bundle\Tests\Functional\Command
    1x in StatusCommandTest::testExecute from Translation\Bundle\Tests\Functional\Command
    1x in SyncCommandTest::testExecute from Translation\Bundle\Tests\Functional\Command
    1x in EditInPlaceControllerTest::testEditAction from Translation\Bundle\Tests\Functional\Controller
    1x in EditInPlaceControllerTest::testEditActionError from Translation\Bundle\Tests\Functional\Controller
    1x in EditInPlaceTest::testActivatedTest from Translation\Bundle\Tests\Functional\Controller
    1x in EditInPlaceTest::testIfUntranslatableLabelGetsDisabled from Translation\Bundle\Tests\Functional\Controller
    1x in EditInPlaceTest::testDeactivatedTest from Translation\Bundle\Tests\Functional\Controller
    1x in WebUIControllerTest::testIndexAction from Translation\Bundle\Tests\Functional\Controller
    1x in WebUIControllerTest::testShowAction from Translation\Bundle\Tests\Functional\Controller
    1x in WebUIControllerTest::testCreateAction from Translation\Bundle\Tests\Functional\Controller
    1x in WebUIControllerTest::testEditAction from Translation\Bundle\Tests\Functional\Controller
    1x in WebUIControllerTest::testDeleteAction from Translation\Bundle\Tests\Functional\Controller

  18x: Since symfony/dependency-injection 5.1: The "Psr\Container\ContainerInterface" autowiring alias is deprecated. Define it explicitly in your app if you want to keep using it. It is being referenced by the "Translation\Bundle\Controller\EditInPlaceController" service.
    3x in CheckMissingCommandTest::setUp from Translation\Bundle\Tests\Functional\Command
    1x in BundleInitializationTest::testRegisterBundle from Translation\Bundle\Tests\Functional
    1x in CatalogueFetcherTest::testFetchCatalogue
    1x in ExtractCommandTest::testExecute from Translation\Bundle\Tests\Functional\Command
    1x in StatusCommandTest::testExecute from Translation\Bundle\Tests\Functional\Command
    1x in SyncCommandTest::testExecute from Translation\Bundle\Tests\Functional\Command
    1x in EditInPlaceControllerTest::testEditAction from Translation\Bundle\Tests\Functional\Controller
    1x in EditInPlaceControllerTest::testEditActionError from Translation\Bundle\Tests\Functional\Controller
    1x in EditInPlaceTest::testActivatedTest from Translation\Bundle\Tests\Functional\Controller
    1x in EditInPlaceTest::testIfUntranslatableLabelGetsDisabled from Translation\Bundle\Tests\Functional\Controller
    1x in EditInPlaceTest::testDeactivatedTest from Translation\Bundle\Tests\Functional\Controller
    1x in WebUIControllerTest::testIndexAction from Translation\Bundle\Tests\Functional\Controller
    1x in WebUIControllerTest::testShowAction from Translation\Bundle\Tests\Functional\Controller
    1x in WebUIControllerTest::testCreateAction from Translation\Bundle\Tests\Functional\Controller
    1x in WebUIControllerTest::testEditAction from Translation\Bundle\Tests\Functional\Controller
    1x in WebUIControllerTest::testDeleteAction from Translation\Bundle\Tests\Functional\Controller

  15x: Since symfony/http-foundation 5.3: "Symfony\Component\HttpFoundation\RequestStack::getMasterRequest()" is deprecated, use "getMainRequest()" instead.
    6x in WebUIControllerTest::testIndexAction from Translation\Bundle\Tests\Functional\Controller
    3x in EditInPlaceTest::testActivatedTest from Translation\Bundle\Tests\Functional\Controller
    3x in EditInPlaceTest::testIfUntranslatableLabelGetsDisabled from Translation\Bundle\Tests\Functional\Controller
    3x in WebUIControllerTest::testShowAction from Translation\Bundle\Tests\Functional\Controller

Other deprecation notices (4)

  4x: Since symfony/twig-bundle 5.2: Accessing the "twig" service directly from the container is deprecated, use dependency injection instead.
    2x in WebUIControllerTest::testIndexAction from Translation\Bundle\Tests\Functional\Controller
    1x in WebUIControllerTest::testShowAction from Translation\Bundle\Tests\Functional\Controller
    1x in WebUIControllerTest::testCreateAction from Translation\Bundle\Tests\Functional\Controller
```

**Review by rvanlaak — APPROVED** [review]

**Comment by bocharsky-bw** [comment]
Thank you for the review, guys!

**Pull request merged**
