### PR TITLE
Add test on showing original "Edit in place" value

### PR DESCRIPTION
**Pull request by rvanlaak**
@Nyholm added a test related to #89

### CODE REVIEW

**Comment by Nyholm** [comment]
Sorry, was I too fast on the merge button. :/

**Comment by rvanlaak** [comment]
... interesting, on itself the test does pass.

**Comment by Nyholm** [comment]
This PR is blocked by #94. I also made a PR to this PR to make sure till will work with the changes in #94

**Comment by Nyholm** [comment]
Awesome. Thank you!

**Pull request merged**
